<a href="dashboard_admin.php" class="btn btn-primary btn-danger">Home</a>
                <a href="gerenciar_categorias.php"  class="btn btn-primary btn-danger ">Categorias</a>
                <a href="gerenciar_produtos.php"  class="btn btn-primary btn-danger " >Produtos</a>
                <a href="gerenciar_usuario.php"  class="btn btn-primary btn-danger ">Usuários</a>
                <a href="relatorio.php" class="btn btn-primary btn-danger">Relatórios</a>